### ISSUE TITLE
Cloudflare Page Rules

### ISSUE THREAD

**Issue by thermokarst** [divshot/docs#5]
In the [guide](http://docs.divshot.com/guides/domains/apex-cloudflare), line 22 states:

> “**We strongly advise against using CloudFlare acceleration. Under 'Active', click the orange cloud icon and disable it. It should show a gray cloud.**” (commit bec1262).

However at [cloudflare](https://support.cloudflare.com/hc/en-us/articles/200168306-Is-there-a-tutorial-for-Page-Rules-) they state:

> “A rule can only apply to a site (or a site's subdomain) under your control and that is on CloudFlare (orange cloud). When a site is taken off CloudFlare (grey cloud or by switching the DNS records away from CloudFlare) the rules will no longer take effect.”

These seem to be conflicting to me. Am I misunderstanding the divshot docs? Thanks!

**Comment by kevinchau** [comment]
Revised: https://github.com/divshot/docs/commit/0e32365d20828f179aa68d4b82f669bf59bb1303

**Comment by thermokarst** [comment]
Thanks @kevinchau! Where does Cloudflare indicate that that apex domains are exempt from the "orange cloud" rule? Besides the Cloudflare doc I linked to in my initial comment, I also see the [following](https://support.cloudflare.com/hc/en-us/articles/200172356-Why-isn-t-a-Page-Rule-working-):
> The number one reason that a Page Rule isn't working, such as URL forwarding, is that the Page Rule you created is on a record that is not proxied by CloudFlare in your DNS settings.

I understand that to be the "orange cloud" setting needs to be on for a domain/subdomain to have page rules applied to it.

I know this stuff is specific to Cloudflare, but the Divshot docs generally seem to be at odds with that. Thanks for all your help, I really appreciate it, and all the great work you all are doing at Divshot!

**Comment by kevinchau** [comment]
It looks like they've deprecated that feature (you used to be able to in the past). I've updated our docs to reflect that.

We are able to apply all page rules via our CDN.

**Comment by thermokarst** [comment]
Thanks @kevinchau!
